### ISSUE TITLE
Warning: viewport meta tags should not be used in _document.js's <Head>

### ISSUE THREAD

**Issue by FinnWoelm** [MarchWorks/nextjs-with-material-ui-styled-components#9]
Thanks for this awesome starter template!

In the latest version of NextJS, the following warning is emitted:

```
Warning: viewport meta tags should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-viewport-meta
```

Looks like the viewport meta tag should be specified in _app.js rather than _document.js: https://github.com/vercel/next.js/blob/master/errors/no-document-viewport-meta.md

**Comment by nblthree** [comment]
Thanks for reporting and sorry for the late response
